version: '3'

services:
  ml-api:
    build: ml-api/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: ml-api
    
  metrics-api:
    build: metrics-api/
    ports: 
      - 8001:8001
    networks:
      - deploy_network
    container_name: metrics-api

  streamlit-ui:
    build: streamlit-ui/
    depends_on:
      - ml-api
      - metrics-api
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit-ui

networks:
  deploy_network:
    driver: bridge
